language: python
python:
  - "2.6"
  - "2.7"
install: 
  - "make install"
  - "pip install coveralls"

script:
  - "make test"
  - "coverage run --source fff setup.py test"
after_success:
    coveralls
